import { useState, useEffect, useContext } from 'react'
import { ThemeCtx } from './ThemeContext.jsx'
import { DARK, LIGHT } from '../theme.js'
import { Btn, StatusBadge, ScoreBar, Tag, Textarea, Divider, Spinner } from './ui/index.jsx'
import { api } from '../api.js'

// ── Confirm Apply Modal ───────────────────────────────────────────────────────
function ConfirmModal({ job, onConfirm, onCancel, dark }) {
  const T = dark ? DARK : LIGHT
  const [step, setStep] = useState('review')
  const [checked, setChecked] = useState(false)

  if (step === 'done') {
    return (
      <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(6px)' }}>
        <div style={{ background: T.surface, borderRadius: 16, padding: 40, textAlign: 'center', maxWidth: 400, border: `1px solid ${T.border}` }}>
          <div style={{ fontSize: 48, marginBottom: 12 }}>🎉</div>
          <div style={{ fontSize: 20, fontWeight: 800, color: T.text, marginBottom: 8 }}>Application Submitted!</div>
          <div style={{ fontSize: 13, color: T.muted, marginBottom: 24 }}>
            Your application to <strong style={{ color: T.text }}>{job.company}</strong> has been submitted successfully.
          </div>
          <Btn variant="primary" onClick={onConfirm} size="lg">Done</Btn>
        </div>
      </div>
    )
  }

  const score = job.score ?? 0

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(6px)' }}>
      <div style={{ background: T.surface, borderRadius: 16, width: 560, maxHeight: '85vh', overflow: 'hidden', display: 'flex', flexDirection: 'column', border: `1px solid ${T.border}`, boxShadow: '0 32px 80px rgba(0,0,0,0.4)' }}>
        {/* Header */}
        <div style={{ padding: '20px 24px', borderBottom: `1px solid ${T.border}`, display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ width: 36, height: 36, borderRadius: 8, background: '#8B5CF620', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18 }}>⚡</div>
          <div>
            <div style={{ fontSize: 16, fontWeight: 800, color: T.text }}>Confirm Application</div>
            <div style={{ fontSize: 12, color: T.muted }}>Human-in-the-loop review — your approval is required</div>
          </div>
          <button onClick={onCancel} style={{ marginLeft: 'auto', background: 'none', border: 'none', cursor: 'pointer', color: T.muted, fontSize: 18 }}>✕</button>
        </div>

        <div style={{ flex: 1, overflowY: 'auto', padding: '20px 24px' }}>
          {/* Job summary */}
          <div style={{ background: dark ? '#1A1A28' : '#F8F8FF', border: `1px solid ${T.border}`, borderRadius: 10, padding: '14px 16px', marginBottom: 16 }}>
            <div style={{ fontSize: 15, fontWeight: 700, color: T.text, marginBottom: 4 }}>{job.title}</div>
            <div style={{ fontSize: 12, color: T.muted, display: 'flex', gap: 12, flexWrap: 'wrap' }}>
              <span>🏢 {job.company}</span>
              <span>📍 {job.location}</span>
              <span style={{ color: '#22C55E', fontWeight: 700 }}>✦ {Math.round(score * 100)}% match</span>
            </div>
          </div>

          {/* Resume preview placeholder */}
          <div style={{ fontSize: 11, fontWeight: 700, color: T.muted, textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 8 }}>Tailored Resume</div>
          <div style={{ borderRadius: 8, overflow: 'hidden', border: `1px solid ${T.border}`, marginBottom: 16, maxHeight: 220, overflowY: 'auto', background: '#fff', padding: '20px 24px' }}>
            <div style={{ textAlign: 'center', borderBottom: '2px solid #1A1A2E', paddingBottom: 10, marginBottom: 12 }}>
              <div style={{ fontSize: 16, fontWeight: 700, letterSpacing: '0.05em', fontFamily: 'DM Sans, sans-serif', color: '#1A1A2E' }}>ISHANI KATHURIA</div>
              <div style={{ fontSize: 10, color: '#555', marginTop: 4 }}>Purdue University · MS AI 2025 · 4.0 GPA</div>
            </div>
            <div style={{ fontSize: 11, color: '#333', lineHeight: 1.6 }}>
              <strong>Tailored for:</strong> {job.title} at {job.company}<br />
              <em>Resume generated by AI — verify before submitting</em>
            </div>
          </div>

          {/* Warning */}
          <div style={{ background: '#F59E0B15', border: '1px solid #F59E0B40', borderRadius: 8, padding: '10px 14px', marginBottom: 16, display: 'flex', gap: 10 }}>
            <span style={{ fontSize: 16, flexShrink: 0 }}>⚠️</span>
            <div style={{ fontSize: 12, color: T.text, lineHeight: 1.5 }}>
              <strong>This action cannot be undone.</strong> The AI will auto-fill and submit the application form on your behalf.
            </div>
          </div>

          {/* Checklist */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 20 }}>
            {[
              'Resume is tailored and accurate',
              'Cover letter looks good',
              `I'm ready to apply to ${job.company}`,
            ].map((item, i) => (
              <label key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer', fontSize: 13, color: T.text }}>
                <input type="checkbox" onChange={i === 2 ? e => setChecked(e.target.checked) : undefined}
                  style={{ width: 16, height: 16, accentColor: '#8B5CF6' }} />
                {item}
              </label>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div style={{ padding: '16px 24px', borderTop: `1px solid ${T.border}`, display: 'flex', gap: 10 }}>
          <Btn variant="secondary" onClick={onCancel} style={{ flex: 1 }}>Go Back</Btn>
          <Btn variant="primary" disabled={!checked} onClick={() => setStep('done')}
            style={{ flex: 2, background: checked ? '#8B5CF6' : undefined }}>
            ⚡ Submit Application
          </Btn>
        </div>
      </div>
    </div>
  )
}

// ── Job Drawer ────────────────────────────────────────────────────────────────
export default function JobDrawer({ job: initialJob, onClose, dark, onRefresh }) {
  const T = dark ? DARK : LIGHT
  const [job, setJob]           = useState(initialJob)
  const [activeTab, setActiveTab] = useState('overview')
  const [notes, setNotes]       = useState('')
  const [coverLetter, setCoverLetter] = useState('')
  const [jdExpanded, setJdExpanded]   = useState(false)
  const [showConfirm, setShowConfirm] = useState(false)
  const [tailoring, setTailoring]     = useState(false)
  const [tailorMsg, setTailorMsg]     = useState('')
  const [updating, setUpdating]       = useState(false)

  // Fetch full job data (focus items only have id)
  useEffect(() => {
    if (!initialJob) return
    if (initialJob._needsFetch) {
      api.job(initialJob.id).then(j => {
        setJob(j)
        setNotes(j.notes || '')
      }).catch(() => {})
    } else {
      setJob(initialJob)
      setNotes(initialJob.notes || '')
    }
    setActiveTab('overview')
    setTailorMsg('')
  }, [initialJob?.id])

  // Fetch cover letter text when switching to that tab
  useEffect(() => {
    if (activeTab === 'cover letter' && job?.resume_path) {
      api.coverLetter(job.id).then(setCoverLetter).catch(() => setCoverLetter(''))
    }
  }, [activeTab, job?.id])

  if (!job) return (
    <div style={{ width: 440, flexShrink: 0, height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: T.surface, borderLeft: `1px solid ${T.border}` }}>
      <Spinner size={28} />
    </div>
  )

  const score = job.score ?? 0
  const pct   = Math.round(score * 100)
  const scoreColor = score >= 0.75 ? T.success : score >= 0.55 ? T.warning : T.danger

  const primaryAction = {
    new:       { label: '✦ Tailor with AI',       color: T.accent,    action: handleTailor },
    // Step 1: just approve (no modal) — job moves to Approved tab
    queued:    { label: '✓ Approve',               color: '#8B5CF6',   action: () => patchStatus('approved') },
    // Step 2: confirm you've actually submitted — job moves to Applied tab
    approved:  { label: '⚡ Mark as Applied',       color: '#8B5CF6',   action: () => setShowConfirm(true) },
    applied:   { label: '📝 Got OA?',              color: '#F59E0B',   action: () => patchStatus('oa') },
    oa:        { label: '🎤 Got Interview?',        color: '#EC4899',   action: () => patchStatus('interview') },
    interview: { label: '🎉 Got Offer?',           color: '#10B981',   action: () => patchStatus('offer') },
    offer:     { label: '🎊 Celebrate!',            color: '#10B981',   action: null },
    rejected:  null,
    skipped:   null,
  }[job.status]

  async function patchStatus(newStatus, extra = {}) {
    setUpdating(true)
    try {
      const updated = await api.patch(job.id, { status: newStatus, ...extra })
      setJob(updated)
      onRefresh?.()
    } catch (e) {
      alert('Error: ' + e.message)
    } finally {
      setUpdating(false)
    }
  }

  async function handleTailor() {
    setTailoring(true)
    setTailorMsg('')
    try {
      const res = await api.tailor(job.id)
      setTailorMsg('✨ ' + res.message)
      const updated = await api.job(job.id)
      setJob(updated)
      onRefresh?.()
    } catch (e) {
      setTailorMsg('❌ ' + e.message)
    } finally {
      setTailoring(false)
    }
  }

  async function saveNotes() {
    await api.patch(job.id, { notes })
    onRefresh?.()
  }

  async function saveCoverLetter() {
    await api.saveCL(job.id, coverLetter)
  }

  // ── Edit tab ──
  const [editForm, setEditForm]   = useState(null)   // null = not open yet
  const [editSaving, setEditSaving] = useState(false)
  const [editMsg, setEditMsg]       = useState('')

  // Populate edit form when switching to edit tab
  useEffect(() => {
    if (activeTab === 'edit') {
      setEditForm({
        title:          job.title         || '',
        company:        job.company       || '',
        location:       job.location      || '',
        url:            job.url           || '',
        status:         job.status        || 'new',
        score:          job.score         ?? '',
        date_applied:   job.date_applied  ? job.date_applied.slice(0,10) : '',
        recruiter:      job.recruiter     || '',
        salary_range:   job.salary_range  || '',
        interview_date: job.interview_date ? job.interview_date.slice(0,10) : '',
        follow_up_date: job.follow_up_date ? job.follow_up_date.slice(0,10) : '',
        rejection_stage:job.rejection_stage || '',
        starred:        job.starred       ? true : false,
      })
      setEditMsg('')
    }
  }, [activeTab, job?.id])

  const setEF = (k, v) => setEditForm(f => ({ ...f, [k]: v }))

  async function saveEdit() {
    setEditSaving(true); setEditMsg('')
    try {
      const payload = {
        title:           editForm.title.trim()          || undefined,
        company:         editForm.company.trim()         || undefined,
        location:        editForm.location.trim()        || undefined,
        url:             editForm.url.trim()             || undefined,
        status:          editForm.status                 || undefined,
        score:           editForm.score !== '' ? parseFloat(editForm.score) : undefined,
        date_applied:    editForm.date_applied           || undefined,
        recruiter:       editForm.recruiter.trim()       || undefined,
        salary_range:    editForm.salary_range.trim()    || undefined,
        interview_date:  editForm.interview_date         || undefined,
        follow_up_date:  editForm.follow_up_date         || undefined,
        rejection_stage: editForm.rejection_stage.trim() || undefined,
        starred:         editForm.starred ? 1 : 0,
      }
      // strip undefineds
      Object.keys(payload).forEach(k => payload[k] === undefined && delete payload[k])
      const updated = await api.patch(job.id, payload)
      setJob(updated)
      setNotes(updated.notes || '')
      onRefresh?.()
      setEditMsg('✓ Saved')
      setTimeout(() => setEditMsg(''), 2000)
    } catch (e) {
      setEditMsg('❌ ' + (e.message || 'Save failed'))
    } finally {
      setEditSaving(false)
    }
  }

  const STATUS_OPTS = ['new','queued','approved','applied','oa','interview','offer','rejected','skipped']

  const drawerTabs = ['overview', 'resume', 'cover letter', 'edit']

  return (
    <>
      {showConfirm && (
        <ConfirmModal job={job} dark={dark}
          onConfirm={async () => {
            setShowConfirm(false)
            await patchStatus('applied', { date_applied: new Date().toISOString().slice(0, 10) })
            onClose()
          }}
          onCancel={() => setShowConfirm(false)}
        />
      )}

      <div style={{
        width: 440, flexShrink: 0, height: '100vh', display: 'flex', flexDirection: 'column',
        background: T.surface, borderLeft: `1px solid ${T.border}`,
        position: 'sticky', top: 0,
      }}>
        {/* Header */}
        <div style={{ padding: '16px 20px', borderBottom: `1px solid ${T.border}`, flexShrink: 0 }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10, marginBottom: 10 }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 15, fontWeight: 800, color: T.text, lineHeight: 1.3, marginBottom: 4 }}>
                {job.starred ? <span style={{ color: '#F59E0B', marginRight: 5 }}>★</span> : null}
                {job.title}
              </div>
              <div style={{ fontSize: 12, color: T.muted, display: 'flex', gap: 6, flexWrap: 'wrap', alignItems: 'center' }}>
                <span style={{ fontWeight: 600, color: T.text }}>{job.company}</span>
                <span>·</span><span>{job.location}</span>
                <span>·</span><Tag>{job.source}</Tag>
              </div>
            </div>
            <div style={{ display: 'flex', gap: 6, alignItems: 'center', flexShrink: 0 }}>
              {/* Star toggle */}
              <button
                onClick={() => patchStatus(job.status, { starred: job.starred ? 0 : 1 })}
                title={job.starred ? 'Unstar' : 'Star'}
                style={{ background: 'none', border: 'none', cursor: 'pointer', color: job.starred ? '#F59E0B' : T.muted, fontSize: 16, padding: 4 }}>
                {job.starred ? '★' : '☆'}
              </button>
              <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: T.muted, fontSize: 18, padding: 4 }}>✕</button>
            </div>
          </div>

          {/* Score + status */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
            <StatusBadge status={job.status} size="md" />
            <div style={{ flex: 1 }}><ScoreBar score={score} height={5} showLabel /></div>
          </div>

          {/* Primary action */}
          {primaryAction && (
            <button
              onClick={tailoring || updating ? undefined : primaryAction.action}
              disabled={tailoring || updating}
              style={{
                width: '100%', padding: '11px 0', borderRadius: 9, border: 'none',
                cursor: tailoring || updating ? 'not-allowed' : 'pointer',
                background: primaryAction.color, color: '#fff', fontSize: 13, fontWeight: 700,
                fontFamily: 'DM Sans, sans-serif', opacity: tailoring || updating ? 0.7 : 1,
                display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
              }}>
              {tailoring ? <><Spinner size={14} color="#fff" /> Tailoring…</> : primaryAction.label}
            </button>
          )}
          {tailorMsg && <div style={{ fontSize: 11, color: T.muted, marginTop: 6, textAlign: 'center' }}>{tailorMsg}</div>}
        </div>

        {/* Tabs */}
        <div style={{ display: 'flex', borderBottom: `1px solid ${T.border}`, flexShrink: 0 }}>
          {drawerTabs.map(t => (
            <button key={t} onClick={() => setActiveTab(t)}
              style={{
                flex: 1, padding: '9px 4px', border: 'none', cursor: 'pointer', background: 'transparent',
                fontFamily: 'DM Sans, sans-serif', fontSize: 11, fontWeight: activeTab === t ? 700 : 500,
                color: activeTab === t ? T.accent : T.muted,
                borderBottom: activeTab === t ? `2px solid ${T.accent}` : '2px solid transparent',
                textTransform: 'capitalize', transition: 'all 0.12s',
              }}>{t}</button>
          ))}
        </div>

        {/* Content */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '16px 20px' }}>
          {/* ── Overview ── */}
          {activeTab === 'overview' && (
            <div>
              {/* JD */}
              <div style={{ marginBottom: 16 }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: T.muted, textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 8 }}>Job Description</div>
                <div style={{ fontSize: 12, color: T.text, lineHeight: 1.7, whiteSpace: 'pre-wrap', maxHeight: jdExpanded ? 'none' : 120, overflow: 'hidden' }}>
                  {job.description || 'No description available.'}
                </div>
                <button onClick={() => setJdExpanded(!jdExpanded)}
                  style={{ background: 'none', border: 'none', cursor: 'pointer', color: T.accent, fontSize: 11, fontWeight: 700, padding: '4px 0', marginTop: 4 }}>
                  {jdExpanded ? '↑ Show less' : '↓ Show more'}
                </button>
              </div>

              <Divider />

              {/* Notes */}
              <div style={{ marginBottom: 16 }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: T.muted, textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 8 }}>Notes</div>
                <Textarea value={notes} onChange={setNotes} placeholder="Add notes about this job…" rows={3} />
                {notes !== (job.notes || '') && (
                  <button onClick={saveNotes} style={{ marginTop: 6, background: 'none', border: 'none', cursor: 'pointer', color: T.accent, fontSize: 11, fontWeight: 700 }}>
                    💾 Save notes
                  </button>
                )}
              </div>

              {/* Interview date */}
              {job.interview_date && (
                <div style={{ background: '#EC489915', border: '1px solid #EC489940', borderRadius: 8, padding: '10px 14px', marginBottom: 12 }}>
                  <div style={{ fontSize: 12, color: '#EC4899', fontWeight: 700 }}>🎤 Interview: {job.interview_date?.slice(0, 10)}</div>
                  <div style={{ fontSize: 11, color: T.muted, marginTop: 3 }}>Prepare your talking points!</div>
                </div>
              )}

              {job.date_applied && (
                <div style={{ fontSize: 12, color: T.muted, marginBottom: 8 }}>📅 Applied: {job.date_applied?.slice(0, 10)}</div>
              )}
              {job.recruiter && (
                <div style={{ fontSize: 12, color: T.muted, marginBottom: 8 }}>👤 Recruiter: {job.recruiter}</div>
              )}
              {job.salary_range && (
                <div style={{ fontSize: 12, color: T.muted, marginBottom: 8 }}>💰 {job.salary_range}</div>
              )}

              <Divider />

              {/* Secondary actions */}
              <div style={{ fontSize: 11, fontWeight: 700, color: T.muted, textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 10 }}>Actions</div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
                {job.url && !job.url.startsWith('manual://') && (
                  <Btn variant="secondary" size="sm" onClick={() => window.open(job.url, '_blank')} style={{ width: '100%' }}>🔗 View Posting</Btn>
                )}
                {job.status === 'new' && (
                  <Btn variant="ghost" size="sm" onClick={() => patchStatus('skipped')} style={{ width: '100%', color: T.muted }}>⏭ Skip</Btn>
                )}
                {job.status === 'new' && (
                  <Btn variant="ghost" size="sm" onClick={() => patchStatus('rejected')} style={{ width: '100%', color: T.danger }}>✕ Reject</Btn>
                )}
                {job.status === 'queued' && (
                  <Btn variant="ghost" size="sm" onClick={() => patchStatus('new')} style={{ width: '100%', color: T.muted }}>↩ Undo Tailor</Btn>
                )}
                {job.status === 'approved' && (
                  <Btn variant="ghost" size="sm" onClick={() => patchStatus('queued')} style={{ width: '100%', color: T.muted }}>↩ Back to Ready</Btn>
                )}
                {['applied', 'oa', 'interview'].includes(job.status) && (
                  <Btn variant="ghost" size="sm" onClick={() => patchStatus('rejected')} style={{ width: '100%', color: T.danger }}>✕ Got Rejected</Btn>
                )}
              </div>
            </div>
          )}

          {/* ── Resume ── */}
          {activeTab === 'resume' && (
            <div>
              {job.status === 'new' || !job.resume_path ? (
                <div style={{ textAlign: 'center', padding: '40px 0', color: T.muted }}>
                  <div style={{ fontSize: 32, marginBottom: 12 }}>◌</div>
                  <div style={{ fontWeight: 600, marginBottom: 6, color: T.text }}>No resume yet</div>
                  <div style={{ fontSize: 12, marginBottom: 20 }}>Tailor this job to generate a customized resume</div>
                  <Btn variant="primary" onClick={handleTailor} disabled={tailoring}>
                    {tailoring ? 'Tailoring…' : '✦ Tailor Now'}
                  </Btn>
                </div>
              ) : (
                <div style={{ textAlign: 'center' }}>
                  <iframe
                    src={api.resumeUrl(job.id)}
                    style={{ width: '100%', height: 500, border: 'none', borderRadius: 8 }}
                    title="Resume PDF"
                  />
                  <a href={api.resumeUrl(job.id)} target="_blank" rel="noopener noreferrer"
                    style={{ display: 'inline-block', marginTop: 10, fontSize: 12, color: T.accent }}>
                    ⬇️ Download PDF
                  </a>
                </div>
              )}
            </div>
          )}

          {/* ── Cover Letter ── */}
          {activeTab === 'cover letter' && (
            <div>
              {!job.resume_path ? (
                <div style={{ textAlign: 'center', padding: '40px 0', color: T.muted }}>
                  <div style={{ fontSize: 32, marginBottom: 12 }}>✉</div>
                  <div style={{ fontWeight: 600, marginBottom: 6, color: T.text }}>No cover letter yet</div>
                  <div style={{ fontSize: 12, marginBottom: 20 }}>Generated automatically when you tailor this job</div>
                  <Btn variant="primary" onClick={handleTailor} disabled={tailoring}>✦ Tailor Now</Btn>
                </div>
              ) : (
                <>
                  <Textarea value={coverLetter} onChange={setCoverLetter} rows={18} style={{ fontSize: 12, lineHeight: 1.7 }} />
                  <div style={{ marginTop: 10, display: 'flex', gap: 8 }}>
                    <Btn variant="secondary" size="sm" onClick={saveCoverLetter}>💾 Save edits</Btn>
                    <a href={api.resumeUrl(job.id).replace('/resume', '/cover_letter')} target="_blank" rel="noopener noreferrer">
                      <Btn variant="ghost" size="sm">⬇ Download</Btn>
                    </a>
                  </div>
                </>
              )}
            </div>
          )}

          {/* ── Edit ── */}
          {activeTab === 'edit' && editForm && (() => {
            const lbl = { fontSize: 11, fontWeight: 700, color: T.muted, textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 4 }
            const inp = { width: '100%', padding: '7px 10px', borderRadius: 7, border: `1px solid ${T.border}`, background: dark ? '#1A1A28' : '#FAFAFA', color: T.text, fontSize: 12, fontFamily: 'DM Sans, sans-serif', outline: 'none', boxSizing: 'border-box' }
            const row = { marginBottom: 12 }
            return (
              <div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0 12px' }}>
                  <div style={{ ...row, gridColumn: '1/-1' }}>
                    <div style={lbl}>Title</div>
                    <input style={inp} value={editForm.title} onChange={e => setEF('title', e.target.value)} />
                  </div>
                  <div style={row}>
                    <div style={lbl}>Company</div>
                    <input style={inp} value={editForm.company} onChange={e => setEF('company', e.target.value)} />
                  </div>
                  <div style={row}>
                    <div style={lbl}>Location</div>
                    <input style={inp} value={editForm.location} onChange={e => setEF('location', e.target.value)} />
                  </div>
                  <div style={{ ...row, gridColumn: '1/-1' }}>
                    <div style={lbl}>Job URL</div>
                    <input style={inp} value={editForm.url} onChange={e => setEF('url', e.target.value)} />
                  </div>
                  <div style={row}>
                    <div style={lbl}>Status</div>
                    <select style={inp} value={editForm.status} onChange={e => setEF('status', e.target.value)}>
                      {STATUS_OPTS.map(s => <option key={s} value={s}>{s.charAt(0).toUpperCase()+s.slice(1)}</option>)}
                    </select>
                  </div>
                  <div style={row}>
                    <div style={lbl}>Score (0–1)</div>
                    <input style={inp} type="number" min={0} max={1} step={0.01} value={editForm.score} onChange={e => setEF('score', e.target.value)} />
                  </div>
                  <div style={row}>
                    <div style={lbl}>Date Applied</div>
                    <input style={inp} type="date" value={editForm.date_applied} onChange={e => setEF('date_applied', e.target.value)} />
                  </div>
                  <div style={row}>
                    <div style={lbl}>Interview Date</div>
                    <input style={inp} type="date" value={editForm.interview_date} onChange={e => setEF('interview_date', e.target.value)} />
                  </div>
                  <div style={row}>
                    <div style={lbl}>Follow-up Date</div>
                    <input style={inp} type="date" value={editForm.follow_up_date} onChange={e => setEF('follow_up_date', e.target.value)} />
                  </div>
                  <div style={row}>
                    <div style={lbl}>Recruiter</div>
                    <input style={inp} value={editForm.recruiter} onChange={e => setEF('recruiter', e.target.value)} placeholder="Name / email" />
                  </div>
                  <div style={{ ...row, gridColumn: '1/-1' }}>
                    <div style={lbl}>Salary Range</div>
                    <input style={inp} value={editForm.salary_range} onChange={e => setEF('salary_range', e.target.value)} placeholder="$40–50/hr" />
                  </div>
                  <div style={{ ...row, gridColumn: '1/-1' }}>
                    <div style={lbl}>Rejection Stage</div>
                    <input style={inp} value={editForm.rejection_stage} onChange={e => setEF('rejection_stage', e.target.value)} placeholder="e.g. OA, Phone screen" />
                  </div>
                  <div style={{ ...row, gridColumn: '1/-1' }}>
                    <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', fontSize: 12, color: T.text }}>
                      <input type="checkbox" checked={editForm.starred} onChange={e => setEF('starred', e.target.checked)}
                        style={{ width: 15, height: 15, accentColor: '#F59E0B' }} />
                      ★ Starred
                    </label>
                  </div>
                </div>

                <Divider />

                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <Btn variant="primary" onClick={saveEdit} disabled={editSaving}>
                    {editSaving ? 'Saving…' : '💾 Save Changes'}
                  </Btn>
                  {editMsg && (
                    <span style={{ fontSize: 12, color: editMsg.startsWith('✓') ? '#22C55E' : '#EF4444' }}>
                      {editMsg}
                    </span>
                  )}
                </div>
              </div>
            )
          })()}
        </div>
      </div>
    </>
  )
}
